version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: task_manager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  redis:
    image: redis:7
    container_name: task_manager_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  api:
    build: .
    container_name: task_manager_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/task_manager
      - REDIS_URL=redis://redis:6379/0
      
  worker:
    build: .
    container_name: task_manager_worker
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/task_manager
      - REDIS_URL=redis://redis:6379/0
      
  flower:
    build: .
    container_name: task_manager_flower
    command: celery -A app.worker.celery flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: 